### ISSUE TITLE
Can't access images on ecodata when IP not whitelisted

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/ecodata#12]
Example with that one :
http://canmove-dev.ekol.lu.se:8080/ecodata/document/download?filename=/2020-11/thumb_0_sft_logo.png
The image is diplayed only if you load it from an IP in the whitelist. If you're not in the whitelist, you get a "403 non-authorised" error

The file ApyKeyFilter explicitly specifies that a method from a controller from ecodata should need either authorization, apikey, or ROLE_ADMIN. Which makes it normal to prevent the access.

Here is Sathish's answer about that:

```
We don’t use /document/download  controller to retrieve images. We have plans to refactor the document controller to serve images based on image permission. 
At the moment, we are using apache proxypass and app config to server images directly from the file system. 
Ecodata app configs/ ecodata_config.properties:
# application config
app_uploads_url=https://ecodata.ala.org.au/uploads/

Apache config:
...
ProxyPreserveHost On
ProxyPass /uploads/ !
….

```

**Comment by mathieuLU** [comment]
I can't make Satish's solution  work through tomcat8.
My temporary fix is to keep using the document controller, and to allow this method by adding :
`
    @PreAuthorise(basicAuth = false)
`
before
`
    def download() {
`

**Comment by magdziarek** [comment]
@mathieuLU I think you've fixed this issue? Can we close it?
The only image that doesn't work is the favicon which throws the below error in the console. 

Mixed Content: The page at 'https://biocollect.biodiversitydata.se/sft' was loaded over HTTPS, but requested an insecure favicon 'http://ecodata.biodiversitydata.se/document/download?filename=/2021-04/favicon.ico'. This request has been blocked; the content must be served over HTTPS. 

It's defined here:
./grails-app/conf/application.yml:   baseURL: "http://ecodata.biodiversitydata.se"
./grails-app/conf/application.yml:  favicon: "${ecodata.baseURL}/document/download?filename=/2021-04/favicon.ico"
I could just hard-code ecodata.baseURL but I know that's  a bad solution.
I tried changing the value for ecodata.baseURL  but then things went wrong.

**Comment by mathieuLU** [comment]
I think the problem comes from the config file

 /data/biocollect/config/biocollect-config.properties
here you have 
ecodata.baseURL=http://ecodata.biodiversitydata.se

try to change it to https ;-)

**Comment by magdziarek** [comment]
I see you've changed it. I was going to do it now :) Closing!
