### ISSUE TITLE
email config needed

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/ecodata#8]
in /data/ecodata/config/ecodata-config.properties - port and host?
# Email config
grails.mail.host = localhost
grails.mail.port = 1025
ecodata.support.email.address = mathieu.blanchet@biol.lu.se
ecodata.system.email.replyTo = ALAlocal<no-reply@ala.org.au>
ecodata.system.email.sender = ALA-local

ERROR:
2020-09-25 08:10:55,854 [pool-87-thread-4] ERROR mail.MailMessageBuilder  - Failed to send email
org.springframework.mail.MailSendException: Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: act-ironport-int.csiro.au, 25; timeout -1;

**Comment by mathieuLU** [comment]
i think we can close that one right ?
